[project]
name = "phones-parsing"
version = "0.1.0"
description = "Parser for phone info from gsmarena site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "requests>=2.32.3",
]
